#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define EEPROM_SIZE 512
#define SERIAL_BAUDRATE 9600
#define WIFI_MAX_RETRY 20
#define DIAGNOSTIC_PW "#DIAGNOSTIC#"

#define ENABLE 1
#define DISABLE 0

#endif