#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define EEPROM_SIZE 512
#define SERIAL_BAUDRATE 9600
#define WIFI_MAX_RETRY 20
#define DIAGNOSTIC_PW "#DIAGNOSTIC#"

#define ENABLE 1
#define DISABLE 0

#define NEED_MACHINE_ID_DATA "#D#1#"
#define MACHINE_ID_DATA_HEADER "#D#1#"
#define NEED_MACHINE_ID_DATA_ACK "#D#1#ACK#"
#define MESSAGE_FOOTER "#T#"
#define MESSAGE_HEADER "#D#"

#endif